# variables:
#   - template: templates/variables/organisation/variablesV0.yaml@templates
#   - template: templates/variables/project/variablesV1.yaml@templates

#The following section should not be modified
# resources:
  # repositories:
  #   - repository: templates
  #     type: github
  #     name: lineten/sre-yml-infrastructure
  #     endpoint: "lineten github"
  #     resources:
  # repositories:
  #   - repository: azuredevops-buildagents
  #     type: github
  #     name: YannickRe/azuredevops-buildagents
  #     endpoint: "lineten github"
  #     ref: refs/heads/main      
name: Create Build Agent

resources:
  repositories:
    - repository: azuredevops-buildagents
      type: github
      name: YannickRe/azuredevops-buildagents
      endpoint: "lineten"
      ref: refs/heads/main

trigger:
  branches:
    include:
      - main

stages:
  - stage: BuildImage
    displayName: Build Image
    pool:
      name: "Azure Pipelines"
    jobs:
      - job: myJob
        timeoutInMinutes: 10
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - bash: echo "Hello world"
      - template: buildagent-generation-template.yml@self
        parameters: 
          image_type: ubuntu2204
          variable_group: Virtual_Machine_Scale_Set
          agent_pool: "Azure Pipelines"
          repository_base_path: .

